#!/usr/bin/env python3
"""Evaluate canonical repo maturity without running external test suites."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

from repo_maturity import (
    ALLOWED_PROFILES,
    MANIFESTS_DIR,
    REPORTS_DIR,
    build_repo_maturity_report,
    load_acceptance_artifact,
    render_repo_maturity_markdown,
    write_repo_maturity_outputs,
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--profile",
        required=True,
        choices=sorted(ALLOWED_PROFILES),
        help="Repo maturity profile to evaluate.",
    )
    parser.add_argument(
        "--acceptance-json",
        type=Path,
        help="Optional acceptance artifact generated by run_repo_maturity_acceptance.py.",
    )
    parser.add_argument("--venue", help="Optional target venue id for scoped submission gating.")
    parser.add_argument(
        "--reports-dir",
        type=Path,
        help="Optional override directory for written repo-maturity reports.",
    )
    parser.add_argument(
        "--manifests-dir",
        type=Path,
        help="Optional override directory for written repo-maturity manifests.",
    )
    parser.add_argument("--write", action="store_true", help="Write markdown/json maturity outputs and manifest.")
    parser.add_argument("--json", action="store_true", help="Emit JSON instead of markdown.")
    parser.add_argument("--strict", action="store_true", help="Exit non-zero unless all strict requirements are met.")
    return parser.parse_args()


def _emit_error(message: str, *, as_json: bool) -> int:
    if as_json:
        print(json.dumps({"error": message}, indent=2))
    else:
        print(f"Error: {message}", file=sys.stderr)
    return 2


def main() -> int:
    args = parse_args()
    selected_venues = [args.venue] if args.venue else None

    try:
        acceptance_artifact = (
            load_acceptance_artifact(args.acceptance_json) if args.acceptance_json else None
        )
        report = build_repo_maturity_report(
            args.profile,
            acceptance_artifact=acceptance_artifact,
            selected_venues=selected_venues,
        )
        writes = (
            write_repo_maturity_outputs(
                args.profile,
                report=report,
                reports_dir=args.reports_dir or REPORTS_DIR,
                manifests_dir=args.manifests_dir or MANIFESTS_DIR,
            )
            if args.write
            else {}
        )
    except ValueError as exc:
        return _emit_error(str(exc), as_json=args.json)

    payload = {"report": report, "writes": writes}
    if args.json:
        print(json.dumps(payload, indent=2))
    else:
        print(render_repo_maturity_markdown(report), end="")
        if writes:
            print("Generated outputs:")
            print(f"- `{writes['report_json']}`")
            print(f"- `{writes['report_md']}`")
            print(f"- `{writes['manifest']}`")

    if args.strict and report["strict_requirement_issues"]:
        return 1
    return 0 if report["readiness"] == "ready" else 1


if __name__ == "__main__":
    raise SystemExit(main())
